import { describe, it, expect, beforeEach, afterEach } from "vitest";
import { mkdtemp, rm, symlink, mkdir, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { execSync } from "node:child_process";
import { generatePrBody, buildPrTitle, findWorktreeForTask } from "../src/commands/merge.js";

let repo: string;
beforeEach(async () => {
  repo = await mkdtemp(join(tmpdir(), "merge-test-"));
  execSync("git init -q", { cwd: repo });
  execSync("git config user.email t@local", { cwd: repo });
  execSync("git config user.name t", { cwd: repo });
  execSync("git commit --allow-empty -q -m init", { cwd: repo });
  execSync("git branch -m master", { cwd: repo });
});
afterEach(async () => {
  await rm(repo, { recursive: true, force: true });
});

describe("buildPrTitle", () => {
  it("prefixes with pi-pro:", () => {
    expect(buildPrTitle("Add /healthz endpoint")).toBe("pi-pro: Add /healthz endpoint");
  });

  it("truncates very long titles", () => {
    const long = "a".repeat(200);
    const title = buildPrTitle(long);
    expect(title.length).toBeLessThanOrEqual(80);
  });

  it("does not truncate a title of exactly 72 characters", () => {
    const exact = "a".repeat(72);
    const title = buildPrTitle(exact);
    expect(title).toBe(`pi-pro: ${exact}`);
  });

  it("truncates a title of exactly 73 characters and adds ellipsis", () => {
    const tooLong = "a".repeat(73);
    const title = buildPrTitle(tooLong);
    expect(title).toBe(`pi-pro: ${"a".repeat(69)}...`);
    expect(title.length).toBeLessThanOrEqual(80);
  });

  it("keeps a short title unchanged apart from the prefix", () => {
    expect(buildPrTitle("hi")).toBe("pi-pro: hi");
  });
});

describe("generatePrBody", () => {
  it("includes the task description", () => {
    const body = generatePrBody({
      taskId: "tsk_abc",
      title: "Add /healthz endpoint",
      branch: "pi-pro/abc",
      changes: ["src/server.ts", "src/server.test.ts"],
      verification: "47/47 tests passing",
    });
    expect(body).toContain("Add /healthz endpoint");
    expect(body).toContain("tsk_abc");
    expect(body).toContain("src/server.ts");
    expect(body).toContain("47/47 tests passing");
  });

  it("includes a checklist of changes", () => {
    const body = generatePrBody({
      taskId: "tsk_x",
      title: "x",
      branch: "pi-pro/x",
      changes: ["a.ts", "b.ts", "c.ts"],
    });
    expect(body).toMatch(/- \[ \] a\.ts/);
    expect(body).toMatch(/- \[ \] b\.ts/);
    expect(body).toMatch(/- \[ \] c\.ts/);
  });

  it("uses markdown formatting suitable for gh pr create --body", () => {
    const body = generatePrBody({
      taskId: "tsk_x",
      title: "x",
      branch: "pi-pro/x",
      changes: [],
    });
    expect(body).toContain("##");
    expect(body.length).toBeGreaterThan(50);
  });

  it("omits the Changes section when no changes are provided", () => {
    const body = generatePrBody({
      taskId: "tsk_x",
      title: "x",
      branch: "pi-pro/x",
      changes: [],
    });
    expect(body).not.toContain("## Changes");
  });

  it("handles many changes without truncation", () => {
    const changes = Array.from({ length: 50 }, (_, i) => `src/file${i}.ts`);
    const body = generatePrBody({
      taskId: "tsk_x",
      title: "x",
      branch: "pi-pro/x",
      changes,
    });
    for (let i = 0; i < 50; i++) {
      expect(body).toContain(`src/file${i}.ts`);
    }
  });

  it("escapes backticks in branch/taskId but preserves them as code spans", () => {
    const body = generatePrBody({
      taskId: "tsk_abc",
      title: "x",
      branch: "pi-pro/abc",
      changes: [],
    });
    expect(body).toContain("`tsk_abc`");
    expect(body).toContain("`pi-pro/abc`");
  });

  it("omits Verification section when not provided", () => {
    const body = generatePrBody({
      taskId: "tsk_x",
      title: "x",
      branch: "pi-pro/x",
      changes: ["a.ts"],
    });
    expect(body).not.toContain("## Verification");
  });

  it("ends with a Generated-by footer", () => {
    const body = generatePrBody({
      taskId: "tsk_x",
      title: "x",
      branch: "pi-pro/x",
      changes: [],
    });
    expect(body).toMatch(/Generated by pi-pro\s*$/);
  });
});

describe("findWorktreeForTask", () => {
  it("finds the worktree for a given task id", async () => {
    const wt = join(repo, ".pi-pro", "worktrees", "tsk_abc");
    execSync(`mkdir -p '${wt}'`);
    execSync(`git worktree add -b pi-pro/abc '${wt}'`, { cwd: repo });
    const found = findWorktreeForTask("tsk_abc", repo);
    expect(found).not.toBeNull();
    expect(found!.branch).toBe("pi-pro/abc");
    expect(found!.path).toBe(wt);
  });

  it("returns null when no worktree matches", () => {
    const found = findWorktreeForTask("tsk_nope", repo);
    expect(found).toBeNull();
  });

  it("returns null when cwd does not exist", () => {
    const found = findWorktreeForTask("tsk_abc", join(repo, "does", "not", "exist"));
    expect(found).toBeNull();
  });

  it("works with a taskId that contains characters safe for the directory name", async () => {
    const taskId = "tsk_safe123";
    const wt = join(repo, ".pi-pro", "worktrees", taskId);
    execSync(`mkdir -p '${wt}'`);
    execSync(`git worktree add -b pi-pro/safe '${wt}'`, { cwd: repo });
    const found = findWorktreeForTask(taskId, repo);
    expect(found).not.toBeNull();
    expect(found!.taskId).toBe(taskId);
  });

  it("works with a symlinked worktree path", async () => {
    const realWt = join(repo, ".pi-pro", "worktrees", "tsk_real");
    const linkWt = join(repo, "link-wt");
    execSync(`mkdir -p '${realWt}'`);
    execSync(`git worktree add -b pi-pro/real '${realWt}'`, { cwd: repo });
    await symlink(realWt, linkWt);
    // findWorktreeForTask joins cwd + .pi-pro/worktrees + taskId, so we point at the real path:
    const found = findWorktreeForTask("tsk_real", repo);
    expect(found).not.toBeNull();
    expect(found!.path).toBe(realWt);
  });
});

import { mergeTask } from "../src/commands/merge.js";

describe("mergeTask", () => {
  it("throws when there is no worktree for the given task", () => {
    expect(() => mergeTask("tsk_does_not_exist", repo)).toThrow(/No worktree found/);
  });
});
